// Automatically generated by the bundler tool from resource.rdf

#define resource_NUM_RESOURCES 10UL

#define resource_AnalogGauge_OFFSET 0UL
#define resource_MatteBlack_OFFSET 20UL
#define resource_ShinyBlack_OFFSET 40UL
#define resource_Cord_OFFSET 60UL
#define resource_GreenGlass_OFFSET 80UL
#define resource_WhiteGlass_OFFSET 100UL
#define resource_RedGlass_OFFSET 120UL
#define resource_BlueGlass_OFFSET 140UL
#define resource_YellowGlass_OFFSET 160UL
#define resource_GreenBezel_OFFSET 180UL
